from tkinter import *

window = Tk()
def weight_calculator():
    gram = float(e2_value.get())*1000
    pounds = float(e2_value.get())*2.20462
    ounce = float(e2_value.get())*35.274
    t1.delete("1.0", END)
    t1.insert(END,gram)
    t2.delete("1.0", END)
    t2.insert(END,pounds)
    t3.delete("1.0", END)
    t3.insert(END,ounce)
g = Label(window, text ="[ Weight Calculator ]")
g.grid(row = 0,column = 1)
e1=Label(window,text="Kg")
e1.grid(row=1,column=0)
e2_value = StringVar()
e2 = Entry(window,textvariable = e2_value)
e2.grid(row = 1,column = 1)
b1 = Button(window,text ="Convert",command = weight_calculator)
b1.grid(row = 2,column = 1)
g1 = Label(window)
g1.grid(row = 3)
n1 = Label(window,text="Grams: ")
n1.grid(row = 4,column = 0)
t1 = Text(window,height = 1,width = 20)
t1.grid(row = 4,column = 1)
n2 = Label(window,text="Pounds: ")
n2.grid(row = 5,column = 0)
t2 = Text(window,height = 1,width = 20)
t2.grid(row = 5,column = 1)
n3 = Label(window,text="Ounces: ")
n3.grid(row = 6,column = 0)
t3 = Text(window,height = 1,width = 20)
t3.grid(row = 6,column = 1)
g2 = Label(window)
g2.grid(row = 7)
window.mainloop()